apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
  namespace: video-platform
  labels:
    app: streamforge
    service: delivery
spec:
  replicas: 3
  selector:
    matchLabels:
      app: streamforge
      service: delivery
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: streamforge
        service: delivery
    spec:
      containers:
      - name: delivery-service
        image: csag095/delivery-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: configmp
        resources:
          requests:
            cpu: "1000m"
            memory: "1Gi"
          limits:
            cpu: "2000m"
            memory: "2Gi"
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 15
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: service
                  operator: In
                  values:
                  - delivery
              topologyKey: "kubernetes.io/hostname"