apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: delivery-service-pdb
  namespace: video-platform
spec:
  minAvailable: 2  
  selector:
    matchLabels:
      app: streamforge
      service: delivery