apiVersion: v1
kind: Service
metadata:
  name: delivery-service
  namespace: video-platform
  labels:
    app: streamforge
    service: delivery
spec:
  selector:
    app: streamforge
    service: delivery
  ports:
  - port: 8001 
    targetPort: 8000  
    name: http
  type: ClusterIP