apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-service
  namespace: video-platform
  labels:
    app: streamforge
    service: upload
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streamforge
      service: upload
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: streamforge
        service: upload
    spec:
      containers:
      - name: upload-service
        image: csag095/upload-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: configmp
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 15