apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: video-platform
  labels:
    app: streamforge
    service: mongodb
spec:
  serviceName: mongodb-service
  replicas: 1  # Single instance for simplicity, can be scaled with proper replication
  selector:
    matchLabels:
      app: streamforge
      service: mongodb
  template:
    metadata:
      labels:
        app: streamforge
        service: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
        readinessProbe:
          exec:
            command:
              - mongo
              - --eval
              - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: streamforge-storage
      resources:
        requests:
          storage: 5Gi