apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: video-platform
  labels:
    app: streamforge
    service: mongodb
spec:
  selector:
    app: streamforge
    service: mongodb
  ports:
  - port: 27017
    targetPort: 27017
    name: mongodb
  clusterIP: None  # we are launching this as a headless service no cluster IP