apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-service
  namespace: video-platform
  labels:
    app: streamforge
    service: upload
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streamforge
      service: upload
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: streamforge
        service: upload
    spec:
      serviceAccountName: sqs-access-sa
      containers:
      - name: upload-service
        image: "{{ .Values.uploadService.image }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: configmp