apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: upload-service-pdb
  namespace: video-platform
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: streamforge
      service: upload