# services/transcoding-service/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcoding-service
  namespace: video-platform
  labels:
    app: streamforge
    service: transcoding
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streamforge
      service: transcoding
  strategy:
    type: Recreate  # Since transcoding is stateful process so the pod identity should not be changed
  template:
    metadata:
      labels:
        app: streamforge
        service: transcoding
    spec:
      serviceAccountName: sqs-access-sa
      containers:
      - name: transcoding-service
        image: "{{ .Values.transcodingService.image }}"
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: configmp
        volumeMounts:
        - name: transcoding-temp
          mountPath: /tmp/transcoding
      volumes:
      - name: transcoding-temp
        emptyDir:
          medium: Memory
          sizeLimit: 2Gi  #We are doing In-memory storage for faster transcoding